# LuxeUI PR Labeler Configuration
# Labels are applied based on file paths changed in PRs


component:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Components/**/*'


theme:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Theme/**/*'


extensions:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Extensions/**/*'


premium:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Components/Premium/**/*'

glass-effects:
  - changed-files:
      - any-glob-to-any-file:
          - 'Sources/LuxeUI/Components/Containers/GlassmorphismContainer.swift'
          - 'Sources/LuxeUI/Components/Containers/RefractiveGlassModifier.swift'


interactions:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Components/Interactions/**/*'


progress:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Components/Progress/**/*'


sliders:
  - changed-files:
      - any-glob-to-any-file: 'Sources/LuxeUI/Components/Sliders/**/*'


documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file: 'Tests/**/*'


ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'


build:
  - changed-files:
      - any-glob-to-any-file:
          - 'Package.swift'
          - 'Package.resolved'


examples:
  - changed-files:
      - any-glob-to-any-file: 'Examples/**/*'
