# SwiftLint Configuration for LuxeUI
# https://realm.github.io/SwiftLint/

# Paths to include/exclude
included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - .swiftpm
  - docs
  - DerivedData

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - T
    - U
    - V

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - r
    - g
    - b
    - a

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Custom rules
custom_rules:
  # Prefer SwiftUI over UIKit
  no_uikit_imports:
    name: "No UIKit Imports"
    regex: "import UIKit"
    message: "Use SwiftUI instead of UIKit for this project"
    severity: warning
    excluded: ".*Tests\\.swift"
  
  # Ensure proper documentation
  missing_docs:
    name: "Missing Documentation"
    regex: "^\\s*(public|open)\\s+(class|struct|enum|protocol|func|var|let)\\s+(?!.*\\/\\/\\/)"
    message: "Public declarations should have documentation comments"
    severity: warning
    excluded: ".*Tests\\.swift"

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  LuxeUI
                    \/\/
  forbidden_pattern: |
                     \/\/
                     \/\/  Copyright

# Reporter type
reporter: "xcode"
